theme: jekyll-theme-midnight
title: Welcome to sesekriri's page!  
description: Hopefully a lot of code will appear here in the future. This page will probably get deleted though. Also, I have chosen dark theme as it is by far the best. Enjoy your stay. 
